# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
# Deploy with Netlify
# baseurl = "https://tech-blog-hugo-framework.netlify.app/"  # Include trailing slash

# Deploy with Cloudflare Pages
baseurl = "https://tech-blog-hugo-framework.pages.dev/"

# title = "Clarity"  # Edit directly from config/_default/languages.toml # alternatively, uncomment this and remove `title` entry from the aforemention file.
copyright = "Copyright © 2008–2018, Steve Francia and the Hugo Authors; all rights reserved."
# canonifyurls = true
paginate = 10
theme = "hugo-clarity"
disqusShortname = ""

DefaultContentLanguage = "en"
# [languages]
# config/_default/languages.toml

# [menus]
# config/_default/menus/menu.en.toml

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# Search
[outputs]
home = ["HTML", "RSS", "JSON"]

